language: node_js
node_js:
- '6.0'
install: npm install
deploy:
  provider: s3
  access_key_id: <access_key_id>
  bucket: <bucket_name>
  region: us-west-2
  secret_access_key:
    secure: SKRKPCNmspguw2bSKFSwuUT0DPFMqOXLV2BGvbzdZiw9e2bAIRcoiSLBYk6gY8uQq07zgXKBVSPeRXc3yVQbxUYFpHpCFSV3vkfYLmcq0ns0muhyqjANp+cQ9S9+daY/OumOgqkOx1bSvY2qV1ImmJCxYrXdYOub8sCmoZAVkPnqGItH4uIVsjwyG70CedyGY0FmLnuubuoEpqqnkWjuuqtwKsWbTRT3OYx1JtgIE+Pl6HsQhjmd4seCZJ1Pv8nrHOl50XRvTNjfXCn0V0RKjqBYa316PAWc7FoI+wZPjSN4xSndFCD2nVZH4X1iW6H5MFuCqDA3FQBtyZEYrwY1nQwRz5A9XQL1s+blgfFU0uxWjLcqZ+nKn/VlCv9kyw0KuzfPKM7RTkzvO6MLkmLYhLupfGKH6nM2YuQ9osfB9UBT2VxK8EEJy+DlM8uPZeMzxDGChU+DXf5UV9/k0RHl5TsqKx5p+ME5YMnzmhJ2vbke+5PdZw05KwZnhGtpAR+qysZKHLaUjR2W8MyM06iq6DVBPtngEZBFQVXsTaPAna4Q2U9NupxNThtfPjIrMRNY4/x4NGPjdu6+8mLKUFO9pxjGFNe/x++R0Jsv8bHBO1c3Jg6wQZYWp/4qtfWIX8cpDI6KieFe380cU3y3dlU3CmweJ3hwGO8RFT3Z47to+08=
